### ISSUE TITLE
Internal transitions seem broken

### ISSUE THREAD

**Issue by brice-morin** [steelbreeze/state.js#14]
Hi,

It seems internal transitions do not work anymore in 5.4.0, probably after some refactoring regarding Choice. See:

```
....\node_modules\state.js\lib\state.com.js:1003
        if (transition.target.isChoice()) {
                             ^
TypeError: Cannot read property 'isChoice' of null
    at traverse (....\node_modules\state.js\lib\state.com.js:1003:30)
    at Evaluator.visitState (....\node_modules\state.js\lib\state.com.js:1100:21)
    at State.accept (....\node_modules\state.js\lib\state.com.js:467:28)
    at Evaluator.visitRegion (....\node_modules\state.js\lib\state.com.js:1049:60)
    at Region.accept (....\node_modules\state.js\lib\state.com.js:182:28)
```

**Comment by brice-morin** [comment]
AFAIK, target is supposed to be null in case of internal transitions. The `if (transition.target.isChoice())`  statement should be protected against null
